export const gameCatalog = [
  {
    id: "speak",
    de: "Sprich mit Mino",
    tr: "Mino ile konuş",
    description: {
      de: "Hör das Wort und sprich es laut nach.",
      tr: "Kelimeyi dinle ve yüksek sesle tekrar et.",
    },
    asset: "microphone",
    color: "#f3def7",
    rounds: 5,
    worlds: ["animals", "food", "vehicles", "body", "clothes", "home", "people", "actions", "jobs", "toys", "school", "sports", "music", "weather", "places", "nature"],
  },
  {
    id: "socialsteps",
    de: "Sicher mit Mino",
    tr: "Mino ile güvende",
    description: {
      de: "Sieh zwei sichere Schritte und finde, was als Nächstes kommt.",
      tr: "İki güvenli adıma bak ve sırada ne olduğunu bul.",
    },
    asset: "raised-hand",
    color: "#dff3e4",
    rounds: 6,
    worlds: ["safety"],
  },
  {
    id: "different",
    de: "Was ist anders?",
    tr: "Hangisi farklı?",
    description: {
      de: "Drei Bilder sind gleich. Finde das eine, das anders ist.",
      tr: "Üç resim aynı. Farklı olan resmi bul.",
    },
    asset: "magnifying-glass-tilted-left",
    color: "#e3f0ff",
    rounds: 6,
    allWorlds: true,
  },
  {
    id: "dailyorder",
    de: "Mein Tagesablauf",
    tr: "Günümün sırası",
    description: {
      de: "Was kommt als Nächstes? Bringe deinen Tag in die richtige Reihenfolge.",
      tr: "Sırada ne var? Gününü doğru sıraya koy.",
    },
    asset: "alarm-clock",
    color: "#ffe7b8",
    rounds: 6,
    worlds: ["routines"],
  },
  {
    id: "opposites",
    de: "Gegensätze",
    tr: "Zıtlıklar",
    description: {
      de: "Finde, was das genaue Gegenteil bedeutet.",
      tr: "Tam tersini anlatan resmi bul.",
    },
    asset: "sun",
    color: "#dcecf9",
    rounds: 6,
    worlds: ["feelings", "weather", "routines"],
  },
  {
    id: "initialletter",
    de: "Anfangsbuchstabe",
    tr: "İlk harfi bul",
    description: {
      de: "Schau das Bild an und finde den ersten Buchstaben.",
      tr: "Resme bak ve ilk harfi bul.",
    },
    asset: "writing-hand",
    color: "#dcecff",
    rounds: 6,
    worlds: [
      "animals", "food", "vehicles", "body", "clothes", "home", "people",
      "actions", "jobs", "toys", "school", "sports", "music", "weather",
      "places", "safety", "nature"
    ],
  },
  {
    id: "story",
    de: "Minos Geschichte",
    tr: "Mino’nun hikâyesi",
    description: {
      de: "Hör eine kurze Geschichte und merke dir, was zuletzt passiert.",
      tr: "Kısa hikâyeyi dinle ve en son ne olduğunu hatırla.",
    },
    asset: "writing-hand",
    color: "#e7e0fb",
    rounds: 4,
    allWorlds: true,
  },
  {
    id: "review",
    de: "Mino-Training",
    tr: "Mino tekrarı",
    description: {
      de: "Mino nimmt genau die Begriffe, die noch Übung brauchen.",
      tr: "Mino, biraz daha çalışılması gereken kelimeleri seçer.",
    },
    asset: "star",
    color: "#fff0b9",
    rounds: 6,
    allWorlds: true,
  },
  {
    id: "explore",
    de: "Entdeckerwelt",
    tr: "Keşif dünyası",
    description: {
      de: "Bewege dich durch eine große Szene und entdecke Dinge.",
      tr: "Büyük sahnede dolaş ve nesneleri keşfet.",
    },
    asset: "sparkles",
    color: "#d9f2d3",
    rounds: 3,
    allWorlds: true,
  },
  {
    id: "draw",
    de: "Malen",
    tr: "Boyama",
    description: {
      de: "Male frei mit dem Finger und sammle einen Stern.",
      tr: "Parmağınla boya ve bir yıldız kazan.",
    },
    asset: "crayon",
    color: "#fbe0ef",
    rounds: 1,
    allWorlds: true,
  },
  {
    id: "listen",
    de: "Hör & Tipp",
    tr: "Dinle ve dokun",
    description: {
      de: "Hör Mino zu und finde das Bild.",
      tr: "Mino’yu dinle, resmi bul.",
    },
    asset: "ear",
    color: "#fce2b5",
    rounds: 6,
    allWorlds: true,
  },
  {
    id: "memory",
    de: "Bilderpaare",
    tr: "Hafıza oyunu",
    description: {
      de: "Dreh die Karten um. Finde die Paare.",
      tr: "Kartları çevir, çiftleri bul.",
    },
    asset: "brain",
    color: "#e2dcf7",
    rounds: 2,
    allWorlds: true,
  },
  {
    id: "match",
    de: "Zusammen gehört’s",
    tr: "Eşleştirelim",
    description: {
      de: "Zieh jedes Bild an seinen Platz.",
      tr: "Resimleri doğru yere sürükle.",
    },
    asset: "puzzle-piece",
    color: "#ceeaf7",
    rounds: 2,
    allWorlds: true,
  },
  {
    id: "sort",
    de: "Richtig einsortiert",
    tr: "Doğru sepete",
    description: {
      de: "Jedes Ding findet seinen Korb.",
      tr: "Her şey kendi sepetine.",
    },
    asset: "basket",
    color: "#e1edc7",
    rounds: 6,
    worlds: [
      "animals",
      "food",
      "vehicles",
      "clothes",
      "home",
      "nature",
      "toys",
    ],
  },
  {
    id: "count",
    de: "Zähl mit Mino",
    tr: "Mino ile say",
    description: {
      de: "Tippe, zähle und finde die Zahl.",
      tr: "Dokun, say ve sayıyı bul.",
    },
    asset: "input-numbers",
    color: "#ffdace",
    rounds: 5,
    allWorlds: true,
  },
  {
    id: "sounds",
    de: "Was hörst du?",
    tr: "Bu ne sesi?",
    description: {
      de: "Klingeln, klopfen, rauschen …",
      tr: "Zil, tıkırtı, rüzgâr …",
    },
    asset: "musical-notes",
    color: "#d1edea",
    rounds: 5,
    worlds: ["sounds"],
  },
  {
    id: "puzzle",
    de: "Bilderpuzzle",
    tr: "Yapboz",
    description: {
      de: "Tausche die Teile. Das Bild wird ganz.",
      tr: "Parçaları değiştir, resmi tamamla.",
    },
    asset: "puzzle-piece",
    color: "#fee0ae",
    rounds: 2,
    worlds: [
      "animals",
      "food",
      "vehicles",
      "feelings",
      "nature",
      "body",
      "clothes",
      "home",
      "people",
      "actions",
      "jobs",
      "sounds",
      "toys",
    ],
  },
  {
    id: "shadow",
    de: "Schattenfreunde",
    tr: "Gölgeler",
    description: {
      de: "Welches Bild passt zum Schatten?",
      tr: "Hangi resim gölgeye ait?",
    },
    asset: "magnifying-glass-tilted-left",
    color: "#e0ddf5",
    rounds: 5,
    worlds: [
      "animals",
      "food",
      "vehicles",
      "clothes",
      "home",
      "nature",
      "toys",
    ],
  },
  {
    id: "missing",
    de: "Was ist weg?",
    tr: "Ne kayboldu?",
    description: {
      de: "Schau genau. Ein Bild versteckt sich!",
      tr: "Dikkatle bak. Bir resim saklanıyor!",
    },
    asset: "sparkles",
    color: "#d8ebd1",
    rounds: 5,
    allWorlds: true,
  },
  {
    id: "pattern",
    de: "Was kommt jetzt?",
    tr: "Sırada ne var?",
    description: {
      de: "Entdecke und ergänze das Muster.",
      tr: "Örüntüyü bul ve tamamla.",
    },
    asset: "rainbow",
    color: "#fbd9e6",
    rounds: 5,
    allWorlds: true,
  },
  {
    id: "lettertrace",
    de: "Buchstaben nachfahren",
    tr: "Harf çizelim",
    description: {
      de: "Folge großen Buchstaben mit dem Finger.",
      tr: "Büyük harfleri parmağınla takip et.",
    },
    asset: "writing-hand",
    color: "#d9ecff",
    rounds: 3,
    worlds: ["letters"],
  },
  {
    id: "trace",
    de: "Zahlen nachfahren",
    tr: "Sayı çizelim",
    description: {
      de: "Folge mit dem Finger den Punkten.",
      tr: "Parmağınla noktaları takip et.",
    },
    asset: "crayon",
    color: "#fce4ad",
    rounds: 3,
    worlds: ["numbers"],
  },
  {
    id: "rhythm",
    de: "Minos Musik",
    tr: "Mino’nun müziği",
    description: {
      de: "Höre die Melodie und spiele sie nach.",
      tr: "Melodiyi dinle ve tekrar çal.",
    },
    asset: "drum",
    color: "#d3e9f9",
    rounds: 3,
    worlds: ["sounds"],
  },
];
export const gameById = Object.fromEntries(gameCatalog.map((g) => [g.id, g]));
export const gamesForWorld = (id) =>
  gameCatalog.filter((g) => g.allWorlds || g.worlds.includes(id));
